# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
